# Generated by Django 3.2.9 on 2021-11-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='Projects/p.png', upload_to='Projects')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolBox.projects')),
            ],
        ),
    ]
