# Generated by Django 3.2.9 on 2021-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolBox', '0002_projectsimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('0', 'Complete'), ('1', 'Not start'), ('2', 'Pending'), ('3', 'Working on')], default=('1', 'Not start'), max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsimages',
            name='Image',
            field=models.ImageField(default='Projects/p.png', upload_to='Projects/'),
        ),
    ]
