# Generated by Django 3.2.9 on 2021-11-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolBox', '0003_auto_20211114_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsimages',
            name='current_image_Max_intensity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsimages',
            name='current_image_Min_intensity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsimages',
            name='current_image_format',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsimages',
            name='current_image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsimages',
            name='current_image_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
