# Generated by Django 3.2.9 on 2021-12-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolBox', '0004_auto_20211121_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendingWithCurrentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blending_image', models.ImageField(default='Blending_images/p.png', upload_to='Blending_images/')),
                ('current_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolBox.projectsimages')),
            ],
        ),
    ]
